/**
 * Serves the pre-built Markdown twin of a page when a client asks for it via
 * HTTP content negotiation (Accept: text/markdown), instead of the default
 * HTML. GitHub Pages (the origin) cannot vary a response by Accept header on
 * its own, so this Worker does that one thing at the edge, reusing the .md
 * files already generated by scripts/markdown_export.py at build time.
 */
export default {
  async fetch(request) {
    const url = new URL(request.url);
    const accept = request.headers.get("Accept") || "";
    const wantsMarkdown = accept.includes("text/markdown");

    if (wantsMarkdown && !url.pathname.endsWith(".md")) {
      const markdownPath = toMarkdownPath(url.pathname);
      if (markdownPath) {
        const markdownUrl = new URL(markdownPath, url.origin);
        const markdownResponse = await fetch(markdownUrl, {
          cf: { cacheTtl: 300, cacheEverything: true },
        });
        if (markdownResponse.ok) {
          const headers = new Headers(markdownResponse.headers);
          headers.set("Content-Type", "text/markdown; charset=utf-8");
          headers.set("Vary", "Accept");
          return new Response(markdownResponse.body, {
            status: 200,
            headers,
          });
        }
      }
    }

    return fetch(request);
  },
};

function toMarkdownPath(pathname) {
  if (pathname === "/" || pathname === "") {
    return "/index.md";
  }
  if (pathname.endsWith("/")) {
    return `${pathname}index.md`;
  }
  if (pathname.endsWith(".html")) {
    return `${pathname.slice(0, -5)}.md`;
  }
  return null;
}
